logging:
  level:
    org.springframework: WARN
    org.apache.hadoop: OFF
spring:
  main:
    show_banner: false
  hadoop:
    fsUri: hdfs://localhost:8020
    resourceManagerHost: localhost
  yarn:
    appType: DATAFLOW
    appName: spring-cloud-dataflow-yarn-app
    applicationBaseDir: /dataflow/apps/
    client:
      clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
      files:
        - "file:${dataflow.yarn.app.appmaster.path:.}/spring-cloud-dataflow-yarn-appmaster-*.jar"
        - "file:${dataflow.yarn.app.container.path:.}/spring-cloud-dataflow-yarn-container-*.jar"
      launchcontext:
        archiveFile: spring-cloud-dataflow-yarn-appmaster-${spring.cloud.dataflow.yarn.version}.jar
      resource:
        memory: 1g
