logging:
  level:
    org.springframework.yarn: DEBUG
server:
  port: 0
endpoints:
  shutdown:
    enabled: true
spring:
  hadoop:
    fsUri: hdfs://localhost:8020
    resourceManagerHost: localhost
  yarn:
    appName: spring-cloud-dataflow-yarn-app
    applicationBaseDir: /dataflow/apps/
    appmaster:
      appmasterClass: org.springframework.cloud.dataflow.yarn.appmaster.DataFlowAppmaster
      keepContextAlive: true
      containercluster:
        enabled: true
        clusters:
          module-template:
            resource:
              priority: 10
              memory: 64
              virtualCores: 1
            launchcontext:
              locality: false
              archiveFile: spring-cloud-dataflow-yarn-container-${spring.cloud.dataflow.yarn.version}.jar
    endpoints:
      containercluster:
        enabled: true
      containerregister:
        enabled: false
