spring:
    main:
        show_banner: false
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appType: XD
        appName: scs-xd-app
        applicationBaseDir: /app/
        applicationDir: /app/scs-xd-app/
        client:
            clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
            files:
              - "file:build/libs/scs-xd-app-container-0.1.0.jar"
              - "file:build/libs/scs-xd-app-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: scs-xd-app-appmaster-0.1.0.jar
            resource:
                memory: 1g
